### ISSUE TITLE
Errors occur if the whole list of categories is not specified

### ISSUE THREAD

**Issue by dnzbk** [Lennong/Extension-AccessOwnership#1]
Tested your extension and found something that could be improved,
The extension allows to work with specific categories which is very useful but if I don't specify a list of all the categories I have I get this kind of errors:
```
INFO    AccessOwnership: Movies Category: Invalid CategoryExt Name: ['Movies'] Name not same as in CATEGORIES Check inst        ructions in the extension settings
INFO    AccessOwnership: Series Category: Invalid CategoryExt Name: ['Series'] Name not same as in CATEGORIES Check inst        ructions in the extension settings
INFO    AccessOwnership: Software Category: Invalid CategoryExt Name: ['Software'] Name not same as in CATEGORIES Check
        instructions in the extension settings
ERROR   Script AccessOwnership with command Test failed
```

### Expected behavior:
The extension should only check the categories I specified in its settings or if it is supposed to be like this, I would like to see some warning that I should specify the whole list of categories.

**Comment by Lennong** [comment]
Yes, I am aware of that bug and the intended function is to only match the added categories that you specify in the extension. It has been fixed among a few others in next release. I have another version coming up any day now with added support for MacOS and some added functionality (detect UID/GID) and that bug will have been adressed.

**Comment by Lennong** [comment]
Version 1.5 released with issue solved.
