### ISSUE TITLE
Ability to override the check if set UID and GUID is present in system

### ISSUE THREAD

**Issue by bouncy99** [Lennong/Extension-AccessOwnership#3]
as the title says, the extension is looking for a valid UID and GUID on the system, however this doesnt consider running in a docker, where folders are mounted into the docker container.  The UID and GUID i may be setting may exist on the host, but not inside the docker container.

**Comment by Lennong** [comment]
It is true you can choose to deploy your container without PUID and PGID but I would not recommend it. As for NZBGet the recommended config are to use it.
[https://docs.linuxserver.io/images/docker-nzbget/#usage](https://docs.linuxserver.io/images/docker-nzbget/#usage)

**Comment by bouncy99** [comment]
appreciate the recommended configs, however unfortunately the latest truenas (electric eel) appears to have some sort of permissions issue, and you can't run it as 1000, or you get a permissions error, hence not running it as documented.

**Comment by Lennong** [comment]
I understand. So it is not a docker issue per se, more of adding support for TrueNAS issue. As of now my extension only support Linux and MacOS, as stated. In a native Docker installation it works just fine, but not officially stated as such.  

I dont see specific support for TrueNAS regarding the PUID and PGID detection in near future.

**Comment by bouncy99** [comment]
i was just thinking generally, but i have worked around the issue using a cronjob instead of this. just thought id mention it.

**Comment by bouncy99** [comment]
hang on, just realised i hadnt thought through my reply to you. i think you may have misunderstood my report. 

"as the title says, the extension is looking for a valid UID and GUID on the system, however this doesnt consider running in a docker, where folders are mounted into the docker container. The UID and GUID i may be setting may exist on the host, but not inside the docker container."

What i mean here is, regardless of what guid or uid the instance is running under, im referring to the permissions to set the files and folders too.   so if i have a user on my host that i want the files changed to, if it doesnt exist in the docker container, your script checks that, and refuses to run.  does that make sense?

**Comment by Lennong** [comment]
Ahh, yes! That makes absolutely more sense! :) Yes, it does refuse to run if UID and GUID do not exists.

I had already an 'override' button for that function in mind (with the intention to be able to set and 'move' files on with a non-existing local UID GUID) and some bits of code for it in the works but never implemented it. I backed out of it as I thought it could generate a lot of extra support need and my time is much more limited now than it was when wrote the extension.

However, as a security measure I think it holds a bit of ground motivationally so I will have a look at it again when time permits.

**Comment by Lennong** [comment]
Reopened as feature request.

**Comment by Lennong** [comment]
Added UID and GID override function in v1.6 release.
